name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.2+1
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_translate: ^4.0.4
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^13.2.3
  json_annotation: ^4.8.1
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqlite3_flutter_libs: ^0.5.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vinque
      fonts:
        - asset: lib/assets/fonts/vinque.otf
