name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  dio: ^5.5.0
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_translate: ^4.0.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  injectable: ^2.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Orpheus
      fonts:
        - asset: assets/fonts/orpheus.ttf
